name: Auto-PR
on:
  push:
    branches: ['develop']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request from develop to main
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: " Automated PR*"
        pr_reviewer: "sindhu"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
